In [64]:
import pandas as pd
import numpy as np
import pyodbc
import subprocess
import io
import os

import matplotlib as plt

# Ignore all warnings
import warnings
warnings.filterwarnings('ignore')

In [65]:
# Path to your Access database
db_path = r'C:\Users\mehak.rafiq.ASKARIBANK\Documents\Projects\model_data\Daily_Dashboard_NTB\Data\Account_Holders_Weekly_be.accdb'

# Connection string
conn_str = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    f"DBQ={db_path};"
)

try:
    # Establish a connection
    with pyodbc.connect(conn_str) as conn:
        cursor = conn.cursor()

        # Retrieve table names
        cursor.tables()
        table_names = [row.table_name for row in cursor if row.table_type == 'TABLE']
        print("Tables in the database:", table_names)

        # Load each table into a Pandas DataFrame
        tables_data = {}
        for table_name in table_names:
            query = f"SELECT * FROM [{table_name}]"
            tables_data[table_name] = pd.read_sql(query, conn)
            print(f"Loaded table: {table_name}")

except pyodbc.Error as e:
    print("Database connection error:", e)
except Exception as e:
    print("Error:", e)

Tables in the database: ['acct_class', 'Acct_holders_tbl', 'Branch_converter_islamic', 'Branch_tbl', 'cif_cnic_sunila-', 'NTB_DB', 'NTB_Reg_Summary', 'NTB_Reg_Summary_3_RGM', 'NTB_Reg_Summary2', 'ntb_tbl', 'RGM_tbl']
Loaded table: acct_class
Loaded table: Acct_holders_tbl
Loaded table: Branch_converter_islamic
Loaded table: Branch_tbl
Loaded table: cif_cnic_sunila-
Loaded table: NTB_DB
Loaded table: NTB_Reg_Summary
Loaded table: NTB_Reg_Summary_3_RGM
Loaded table: NTB_Reg_Summary2
Loaded table: ntb_tbl
Loaded table: RGM_tbl

In [66]:
# Create a new folder called './Data/CSVs' if it doesn't exist
# Creat in a one directory up
os.makedirs('./Data/CSVs', exist_ok=True)


# Save each table as a separate CSV file in the './Data/CSVs' folder
for table_name, df in tables_data.items():
    csv_path = os.path.join('./Data/CSVs', f"{table_name}.csv")
    df.to_csv(csv_path, index=False)
    print(f"Saved {table_name} to {csv_path}")

Saved acct_class to ./Data/CSVs\acct_class.csv
Saved Acct_holders_tbl to ./Data/CSVs\Acct_holders_tbl.csv
Saved Branch_converter_islamic to ./Data/CSVs\Branch_converter_islamic.csv
Saved Branch_tbl to ./Data/CSVs\Branch_tbl.csv
Saved cif_cnic_sunila- to ./Data/CSVs\cif_cnic_sunila-.csv
Saved NTB_DB to ./Data/CSVs\NTB_DB.csv
Saved NTB_Reg_Summary to ./Data/CSVs\NTB_Reg_Summary.csv
Saved NTB_Reg_Summary_3_RGM to ./Data/CSVs\NTB_Reg_Summary_3_RGM.csv
Saved NTB_Reg_Summary2 to ./Data/CSVs\NTB_Reg_Summary2.csv
Saved ntb_tbl to ./Data/CSVs\ntb_tbl.csv
Saved RGM_tbl to ./Data/CSVs\RGM_tbl.csv

In [67]:
# Path to ntb_reg_tbl
ntb_reg_tbl_csv_path = os.path.join('./Data/CSVs', 'NTB_Reg_Summary.csv')

# Load the CSV file into a DataFrame
ntb_reg_tbl_df = pd.read_csv(ntb_reg_tbl_csv_path)

# Print Shape of the DataFrame
print(f"Shape of the DataFrame: {ntb_reg_tbl_df.shape}")

# Display the DataFrame
ntb_reg_tbl_df.head()

Shape of the DataFrame: (354815, 15)

,CUSTOMER_NO,CUST_AC_NO,REGION_DESC,Open_Date_,Registration_Date,Last_Login_Date,Login_Bracket,Accounts,AREA,BRANCH_CODE,BRANCH_NAME,RGM,ROM,Registration_Remarks,Branch_
0,347,166******2311,Central Region-II,2024-04-25,01/22/2021,6-21-2024,Older,1,Area Sargodha,166,Mianwali Branch,Mr. Tariq Mehmood Bhatti,Mr. Syed Tariq Ali Burney,Registered,Mianwali Branch -- Area Sargodha ~~ Mr. Tariq ...
1,390,008******0691,North Region-II,2025-04-24,NaN,NaN,NaN,1,Area Islamabad - I,8,"Jinnah Avenue Branch, Islamabad",Mr. Adnan Hassan,Mr. Muhammad Tanveer Nazar,Not Registered,"Jinnah Avenue Branch, Islamabad -- Area Islama..."
2,477,252******9956,North Region-III,2025-02-03,NaN,NaN,NaN,1,Area Wah,252,Fateh Jang Branch,Raja Waheed Zaman,Mr. Imran Hussain,Not Registered,Fateh Jang Branch -- Area Wah ~~ Raja Waheed Z...
3,478,442******0533,North Region-I,2024-09-05,11/25/2020,5-2-2025,30 Days Active,1,Area Rawalpindi - II,442,Business District Bahria Town,Mr. Khurram Mukthyar,Mr. Syed Tanzeem Abbas Rizvi,Registered,Business District Bahria Town -- Area Rawalpin...
4,489,078******3454,North Region-I,2024-01-10,NaN,NaN,NaN,1,Area Rawalpindi - I,78,"Adyala Road Branch, Rawalpindi",Mr. Khurram Mukthyar,Mr. Syed Tanzeem Abbas Rizvi,Not Registered,"Adyala Road Branch, Rawalpindi -- Area Rawalpi..."

In [68]:
# Find Unique values in Login_Bracket
print(ntb_reg_tbl_df['Login_Bracket'].unique())

['Older' nan '30 Days Active' 'Zero Activity']

In [69]:
# Convert date columns to datetime
ntb_reg_tbl_df['Registration_Date'] = pd.to_datetime(ntb_reg_tbl_df['Registration_Date'])
ntb_reg_tbl_df['Open_Date_'] = pd.to_datetime(ntb_reg_tbl_df['Open_Date_'])

# Create mask for records where Registration_Date is older than Open_Date_
older_reg_mask = ntb_reg_tbl_df['Registration_Date'] < ntb_reg_tbl_df['Open_Date_']

# Update Registration_Remarks where mask is True
ntb_reg_tbl_df.loc[older_reg_mask, 'Registration_Remarks'] = 'Already Registered'

# Count number of updates
num_updates = older_reg_mask.sum()

print(f"Number of records updated to 'Already Registered': {num_updates}")

Number of records updated to 'Already Registered': 24544

In [70]:
# Len of CUST_AC_NO
print(len(ntb_reg_tbl_df['CUST_AC_NO'].unique()))

# Percentage of records updated to 'Already Registered'
print(f"Percentage of records updated to 'Already Registered': {num_updates / len(ntb_reg_tbl_df) * 100}%")

334136
Percentage of records updated to 'Already Registered': 6.917407663148402%

In [72]:
# Convert Last_Login_Da to datetime
ntb_reg_tbl_df['Last_Login_Date'] = pd.to_datetime(ntb_reg_tbl_df['Last_Login_Date'])

# Get current date
current_date = pd.Timestamp.now()

# Create conditions for different time brackets
last_30_days = current_date - pd.Timedelta(days=30)
last_90_days = current_date - pd.Timedelta(days=90) 
last_year = current_date - pd.Timedelta(days=365)

# Create Login_Bracket column
def get_login_bracket(login_date, registration_date):
    if pd.isna(login_date):
        if pd.notna(registration_date):
            return 'More than a Year'
        return 'Not Registered'
    elif login_date >= last_30_days:
        return 'Last 30 Days'
    elif login_date >= last_90_days:
        return 'Last 90 Days'
    elif login_date >= last_year:
        return 'Previous Year'
    else:
        return 'More than a Year'

ntb_reg_tbl_df['Login_Bracket'] = ntb_reg_tbl_df.apply(
    lambda x: get_login_bracket(x['Last_Login_Date'], x['Registration_Date']), 
    axis=1
)

# Print value counts to see distribution
print("\nLogin Bracket Distribution:")
value_counts = ntb_reg_tbl_df['Login_Bracket'].value_counts(dropna=False)
print(value_counts)
print(f"\nTotal: {value_counts.sum()}")
# Create a bar chart comparing months between 2024 and 2025
# First extract year and month from Open_Date_
ntb_reg_tbl_df['Year'] = ntb_reg_tbl_df['Open_Date_'].dt.year
ntb_reg_tbl_df['Month'] = ntb_reg_tbl_df['Open_Date_'].dt.month

# Get monthly counts for each year
monthly_counts = ntb_reg_tbl_df.groupby(['Year', 'Month']).size().reset_index(name='Count')

# Filter for just 2024 and 2025
monthly_counts = monthly_counts[monthly_counts['Year'].isin([2024, 2025])]

# Create the bar plot
plt.figure(figsize=(12, 6))
bar_width = 0.35

# Plot bars for each year
plt.bar(monthly_counts[monthly_counts['Year']==2024]['Month'] - bar_width/2, 
        monthly_counts[monthly_counts['Year']==2024]['Count'],
        bar_width, label='2024')
plt.bar(monthly_counts[monthly_counts['Year']==2025]['Month'] + bar_width/2,
        monthly_counts[monthly_counts['Year']==2025]['Count'], 
        bar_width, label='2025')

plt.xlabel('Month')
plt.ylabel('Number of Accounts')
plt.title('Monthly Account Distribution: 2024 vs 2025')
plt.legend()
plt.xticks(range(1,13))
plt.grid(True, alpha=0.3)
# Save plot with datetime stamp
current_time = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')
save_path = os.path.join('./Figures', f'monthly_accounts_{current_time}.png')

# Create Figures directory if it doesn't exist
os.makedirs('./Figures', exist_ok=True)

plt.savefig(save_path, bbox_inches='tight', dpi=300)

plt.show()

# Print summary statistics
print("\nMonthly Account Summary:")
print(monthly_counts.sort_values(['Year', 'Month']))

Login Bracket Distribution:
Login_Bracket
Not Registered      161520
Last 30 Days        120128
Previous Year        25845
More than a Year     23724
Last 90 Days         23598
Name: count, dtype: int64

Total: 354815

TypeError: 'module' object is not callable

In [54]:
# Convert date columns to datetime with consistent format handling
ntb_reg_tbl_df['Registration_Date'] = pd.to_datetime(ntb_reg_tbl_df['Registration_Date'], errors='coerce')
ntb_reg_tbl_df['Open_Date_'] = pd.to_datetime(ntb_reg_tbl_df['Open_Date_'], errors='coerce')

# Create mask for valid onboarding calculation (both dates exist and registration after opening)
valid_onboarding_mask = (~ntb_reg_tbl_df['Registration_Date'].isna()) & (~ntb_reg_tbl_df['Open_Date_'].isna()) & (ntb_reg_tbl_df['Registration_Date'] >= ntb_reg_tbl_df['Open_Date_'])

# Calculate days to onboard
ntb_reg_tbl_df.loc[valid_onboarding_mask, 'Days_to_Onboard'] = (
    ntb_reg_tbl_df.loc[valid_onboarding_mask, 'Registration_Date'] - 
    ntb_reg_tbl_df.loc[valid_onboarding_mask, 'Open_Date_']
).dt.days

# Get overall average
avg_days_to_onboard = ntb_reg_tbl_df['Days_to_Onboard'].mean()
print(f"Average days to onboard: {avg_days_to_onboard:.2f}")

# Get average by region
region_onboarding = ntb_reg_tbl_df.groupby('REGION_DESC')['Days_to_Onboard'].mean().reset_index()
print("\nAverage onboarding time by region:")
print(region_onboarding.sort_values('Days_to_Onboard'))

Average days to onboard: 59.78

Average onboarding time by region:
           REGION_DESC  Days_to_Onboard
0     Central Region-I        46.172607
3    IB Central Lahore        48.664978
10     South Region-II        54.062864
4             IB North        56.813755
5     IB South Karachi        57.263505
9       South Region-I        62.085112
7      North Region-II        62.843910
2   Central Region-III        63.605555
6       North Region-I        65.548828
8     North Region-III        68.236956
1    Central Region-II        72.604690

In [55]:
# Create bins for customers with login data
login_mask = ~ntb_reg_tbl_df['Last_Login_Date'].isna()
current_date = pd.Timestamp.now()

# Calculate days since last login
ntb_reg_tbl_df.loc[login_mask, 'Days_Since_Last_Login'] = (
    current_date - ntb_reg_tbl_df.loc[login_mask, 'Last_Login_Date']
).dt.days

# Create frequency categories 
def get_login_frequency(days):
    if pd.isna(days):
        return 'No Login'
    elif days <= 7:
        return 'Weekly'
    elif days <= 30:
        return 'Monthly'
    elif days <= 90:
        return 'Quarterly'
    else:
        return 'Inactive'

ntb_reg_tbl_df['Login_Frequency'] = ntb_reg_tbl_df['Days_Since_Last_Login'].apply(get_login_frequency)

# Update 'No Login' to 'Not Registered' when Registration_Remarks is 'Not Registered'
not_registered_mask = (ntb_reg_tbl_df['Login_Frequency'] == 'No Login') & (ntb_reg_tbl_df['Registration_Remarks'] == 'Not Registered')
ntb_reg_tbl_df.loc[not_registered_mask, 'Login_Frequency'] = 'Not Registered'

# Verify the changes
print("\nUpdated Login Frequency Distribution:")
updated_freq_dist = ntb_reg_tbl_df['Login_Frequency'].value_counts().reset_index()
updated_freq_dist.columns = ['Frequency', 'Count']
print(updated_freq_dist)

# Calculate frequency distribution
login_frequency_dist = ntb_reg_tbl_df['Login_Frequency'].value_counts().reset_index()
login_frequency_dist.columns = ['Frequency', 'Count']

print("\nLogin Frequency Distribution:")
print(login_frequency_dist)

# Calculate by region
region_frequency = pd.crosstab(
    ntb_reg_tbl_df['REGION_DESC'], 
    ntb_reg_tbl_df['Login_Frequency'],
    normalize='index'
) * 100

print("\nLogin Frequency by Region (%):")
print(region_frequency)


# Define a clean order for the categories
category_order = ['Weekly', 'Monthly', 'Quarterly', 'Inactive', 'No Login', 'Not Registered']
# Filter to only include categories in our data
valid_categories = [cat for cat in category_order if cat in login_frequency_dist['Frequency'].values]
# Filter and sort the dataframe
sorted_dist = login_frequency_dist[login_frequency_dist['Frequency'].isin(valid_categories)]
sorted_dist = sorted_dist.set_index('Frequency').reindex(valid_categories).reset_index()


# Calculate login frequency by RGM
rgm_frequency = pd.crosstab(
    ntb_reg_tbl_df['RGM'],
    ntb_reg_tbl_df['Login_Frequency'],
    normalize='index'
) * 100

# Calculate active user rate (Weekly + Monthly) by RGM
if 'Weekly' in rgm_frequency.columns and 'Monthly' in rgm_frequency.columns:
    active_cols = ['Weekly', 'Monthly']
    rgm_active_rate = rgm_frequency[active_cols].sum(axis=1).sort_values(ascending=False)
    
    print("\nTop 10 RGMs by Active User Rate (Weekly + Monthly):")
    print(rgm_active_rate.head(10).round(1))
    
    # Save RGM active user rates
    rgm_active_rate = rgm_active_rate.reset_index()
    rgm_active_rate.columns = ['RGM', 'Active_User_Rate']
    rgm_active_rate.to_excel('./Notebook_reports/rgm_active_user_rates.xlsx', index=False)

Updated Login Frequency Distribution:
        Frequency   Count
0  Not Registered  161520
1          Weekly   64458
2         Monthly   56219
3        Inactive   28308
4       Quarterly   23320
5        No Login   20990

Login Frequency Distribution:
        Frequency   Count
0  Not Registered  161520
1          Weekly   64458
2         Monthly   56219
3        Inactive   28308
4       Quarterly   23320
5        No Login   20990

Login Frequency by Region (%):
Login_Frequency      Inactive    Monthly   No Login  Not Registered  \
REGION_DESC
Central Region-I     8.187903  18.853391   6.864503       34.686198
Central Region-II    7.561892  13.887981   3.930060       54.832911
Central Region-III   9.446761  14.936139   4.433856       47.657336
IB Central Lahore    6.390369  15.168739   3.153740       51.529505
IB North             6.418658  15.443331   2.567463       50.794140
IB South Karachi     7.980170  13.689429   2.454822       54.829682
North Region-I       5.510402  16.395747   3.900220       47.096560
North Region-II      6.398111  18.525286   2.971355       42.543502
North Region-III     4.444744  15.149168   2.538892       55.771432
South Region-I      11.697350  17.035958   9.410225       38.107843
South Region-II     13.264800  13.574370  19.669402       30.705879

Login_Frequency     Quarterly     Weekly
REGION_DESC
Central Region-I     6.839247  24.568759
Central Region-II    5.758232  14.028924
Central Region-III   7.150420  16.375488
IB Central Lahore    6.698244  17.059404
IB North             6.530455  18.245952
IB South Karachi     7.908204  13.137694
North Region-I       5.645862  21.451209
North Region-II      5.045962  24.515784
North Region-III     5.158597  16.937167
South Region-I       7.533534  16.215091
South Region-II      9.295873  13.489676

Top 10 RGMs by Active User Rate (Weekly + Monthly):
RGM
Mr. Sarfraz Nazar Chattha    43.4
Mr. Adnan Hassan             43.0
Mr. Khurram Mukthyar         37.8
Mr. Ahmed Bilal Rashid       33.7
Mr. Faisal Naveed Iqbal      33.3
Mr. Tahir Saeed              32.2
Raja Waheed Zaman            32.1
Rao Tauqeer Iqbal            31.3
Mr. Tariq Mehmood Bhatti     27.9
Mr. Irshad Ali Zangejo       27.1
dtype: float64

In [56]:
# Make sure dates are in datetime format
ntb_reg_tbl_df['Registration_Date'] = pd.to_datetime(ntb_reg_tbl_df['Registration_Date'], errors='coerce')
ntb_reg_tbl_df['Open_Date_'] = pd.to_datetime(ntb_reg_tbl_df['Open_Date_'], errors='coerce')

# Initialize Days_to_Onboard column as NaN
ntb_reg_tbl_df['Days_to_Onboard'] = np.nan

# Create a mask for eligible records:
# 1. Not 'Already Registered'
# 2. Has both dates
# 3. Registration date is after or equal to open date
eligible_mask = (
    (ntb_reg_tbl_df['Registration_Remarks'] != 'Already Registered') & 
    (~ntb_reg_tbl_df['Registration_Date'].isna()) & 
    (~ntb_reg_tbl_df['Open_Date_'].isna()) & 
    (ntb_reg_tbl_df['Registration_Date'] >= ntb_reg_tbl_df['Open_Date_'])
)

# Calculate days to onboard only for eligible records
ntb_reg_tbl_df.loc[eligible_mask, 'Days_to_Onboard'] = (
    ntb_reg_tbl_df.loc[eligible_mask, 'Registration_Date'] - 
    ntb_reg_tbl_df.loc[eligible_mask, 'Open_Date_']
).dt.days

# Create days_to_onboard categories
def get_onboarding_bracket(days):
    if pd.isna(days):
        return 'Not Registered'
    elif days <= 5:
        return '5 days or less'
    elif days <= 10:
        return '6-10 days'
    elif days <= 30:
        return '11-30 days'
    elif days <= 180:
        return '1-6 months'
    else:
        return 'More than 6 months'

# Apply the binning function to eligible records
ntb_reg_tbl_df['Onboarding_Time_Bracket'] = 'Not Registered'  # Default value
ntb_reg_tbl_df.loc[eligible_mask, 'Onboarding_Time_Bracket'] = ntb_reg_tbl_df.loc[eligible_mask, 'Days_to_Onboard'].apply(get_onboarding_bracket)

# Update Onboarding_Time_Bracket to "Already Registered" for customers with Registration_Remarks = "Already Registered"
already_registered_mask = ntb_reg_tbl_df['Registration_Remarks'] == 'Already Registered'
ntb_reg_tbl_df.loc[already_registered_mask, 'Onboarding_Time_Bracket'] = 'Already Registered'

# Summary statistics
valid_days = ntb_reg_tbl_df.loc[eligible_mask, 'Days_to_Onboard']
print(f"\nDays to Onboard - Summary Statistics:")
print(f"Count: {valid_days.count()}")
print(f"Mean: {valid_days.mean():.2f} days")
print(f"Median: {valid_days.median():.0f} days")
print(f"Min: {valid_days.min():.0f} days")
print(f"Max: {valid_days.max():.0f} days")

# Distribution of onboarding time brackets
print("\nOnboarding Time Bracket Distribution:")
onboard_dist = ntb_reg_tbl_df['Onboarding_Time_Bracket'].value_counts().sort_index()
print(onboard_dist)

# Exclude 'Not Registered' and 'Already Registered' for percentage calculation of normal onboarding times
normal_onboarding_mask = eligible_mask
onboard_dist_pct = ntb_reg_tbl_df.loc[normal_onboarding_mask, 'Onboarding_Time_Bracket'].value_counts(normalize=True) * 100
print("\nOnboarding Time Bracket Distribution (% of normally registered customers):")
print(onboard_dist_pct.sort_index().round(2))

# Create a filtered dataframe for non-'Already Registered' users for regional and RGM analysis
# This is needed to get accurate regional and RGM insights about normal onboarding patterns
real_ntb_reg_tbl_df = ntb_reg_tbl_df[ntb_reg_tbl_df['Registration_Remarks'] != 'Already Registered']

# Regional analysis of onboarding time brackets
region_onboard = pd.crosstab(
    real_ntb_reg_tbl_df['REGION_DESC'],
    real_ntb_reg_tbl_df['Onboarding_Time_Bracket'],
    normalize='index'
) * 100

print("\nDays to Onboard by Region (%):")
if 'Not Registered' in region_onboard.columns:
    # Move 'Not Registered' to the end for better readability
    cols = [col for col in region_onboard.columns if col != 'Not Registered'] + ['Not Registered']
    region_onboard = region_onboard[cols]

print(region_onboard.round(1))

# Save the region analysis
region_onboard.to_excel('./Notebook_reports/region_onboarding_time.xlsx')

# Additional analysis: RGM-level onboarding performance
rgm_onboard = pd.crosstab(
    real_ntb_reg_tbl_df['RGM'],
    real_ntb_reg_tbl_df['Onboarding_Time_Bracket'],
    normalize='index'
) * 100

# Calculate key metrics for RGMs
rgm_metrics = real_ntb_reg_tbl_df.groupby('RGM').agg(
    Total_Accounts=('CUSTOMER_NO', 'count'),
    Registered_Count=('Registration_Date', lambda x: x.notna().sum()),
    Average_Days_to_Onboard=('Days_to_Onboard', 'mean')
).reset_index()

# Calculate registration rate
rgm_metrics['Registration_Rate'] = (rgm_metrics['Registered_Count'] / rgm_metrics['Total_Accounts'] * 100).round(1)

# Calculate % of quick onboarders (<=10 days)
quick_onboarders = pd.crosstab(
    real_ntb_reg_tbl_df['RGM'],
    real_ntb_reg_tbl_df['Onboarding_Time_Bracket'].isin(['5 days or less', '6-10 days']),
    normalize='index'
) * 100

if True in quick_onboarders.columns:
    rgm_metrics['Quick_Onboarding_Rate'] = quick_onboarders[True].round(1)
else:
    rgm_metrics['Quick_Onboarding_Rate'] = 0

# Sort by Quick Onboarding Rate
rgm_metrics = rgm_metrics.sort_values('Quick_Onboarding_Rate', ascending=False)

print("\nRGM Performance in Onboarding:")
print(rgm_metrics.head(10))  # Top 10 RGMs

# Save RGM analysis
rgm_metrics.to_excel('./Notebook_reports/rgm_onboarding_performance.xlsx', index=False)

Days to Onboard - Summary Statistics:
Count: 168751
Mean: 59.78 days
Median: 26 days
Min: 0 days
Max: 489 days

Onboarding Time Bracket Distribution:
Onboarding_Time_Bracket
1-6 months             59971
11-30 days             57277
5 days or less         19739
6-10 days              16222
Already Registered     24544
More than 6 months     15542
Not Registered        161520
Name: count, dtype: int64

Onboarding Time Bracket Distribution (% of normally registered customers):
Onboarding_Time_Bracket
1-6 months            35.54
11-30 days            33.94
5 days or less        11.70
6-10 days              9.61
More than 6 months     9.21
Name: proportion, dtype: float64

Days to Onboard by Region (%):
Onboarding_Time_Bracket  1-6 months  11-30 days  5 days or less  6-10 days  \
REGION_DESC
Central Region-I               18.7        23.6             8.3        7.9
Central Region-II              14.8        13.6             4.3        3.6
Central Region-III             16.5        16.3             6.0        5.0
IB Central Lahore              13.9        19.0             5.0        4.9
IB North                       15.5        16.8             4.8        4.2
IB South Karachi               13.2        13.5             6.1        5.2
North Region-I                 18.7        15.5             5.0        3.4
North Region-II                21.4        19.2             4.0        4.0
North Region-III               17.4        13.5             2.7        2.6
South Region-I                 20.3        18.4             8.6        5.7
South Region-II                25.6        19.6            10.8        7.5

Onboarding_Time_Bracket  More than 6 months  Not Registered
REGION_DESC
Central Region-I                        3.7            37.8
Central Region-II                       5.8            57.8
Central Region-III                      5.6            50.6
IB Central Lahore                       3.0            54.1
IB North                                4.1            54.7
IB South Karachi                        4.1            57.8
North Region-I                          5.0            52.3
North Region-II                         5.1            46.2
North Region-III                        4.3            59.5
South Region-I                          6.5            40.5
South Region-II                         3.1            33.4

RGM Performance in Onboarding:
                         RGM  Total_Accounts  Registered_Count  \
0           Mr. Adnan Hassan           32752             17618
1     Mr. Ahmed Bilal Rashid           24081             10905
2    Mr. Faisal Naveed Iqbal           31600             18787
3     Mr. Irshad Ali Zangejo           31464             20950
4       Mr. Khurram Mukthyar           35241             16814
5   Mr. Khurrum Iqbal Shamsi           11855              4998
6  Mr. Sarfraz Nazar Chattha           36375             22641
7            Mr. Tahir Saeed           24111             11056
8   Mr. Tariq Mehmood Bhatti           46459             19615
9          Raja Waheed Zaman           27852             11289

   Average_Days_to_Onboard  Registration_Rate  Quick_Onboarding_Rate
0                62.843910               53.8                    NaN
1                56.813755               45.3                    NaN
2                62.085112               59.5                    NaN
3                54.062864               66.6                    NaN
4                65.548828               47.7                    NaN
5                57.263505               42.2                    NaN
6                46.172607               62.2                    NaN
7                48.664978               45.9                    NaN
8                72.604690               42.2                    NaN
9                68.236956               40.5                    NaN

In [57]:
# Extract month from registration date
ntb_reg_tbl_df['Registration_Month'] = ntb_reg_tbl_df['Registration_Date'].dt.to_period('M')

# Calculate monthly onboarding times
monthly_onboarding = ntb_reg_tbl_df.groupby('Registration_Month')['Days_to_Onboard'].agg(['mean', 'median', 'count']).reset_index()
monthly_onboarding = monthly_onboarding.sort_values('Registration_Month')

In [58]:
# Branch performance metrics
branch_metrics = ntb_reg_tbl_df.groupby('BRANCH_NAME').agg(
    Total_Accounts=('CUSTOMER_NO', 'count'),
    Registered_Count=('Registration_Date', lambda x: x.notna().sum()),
    Avg_Days_to_Onboard=('Days_to_Onboard', 'mean')
).reset_index()

# Calculate registration rate and add REGION_DESC
branch_metrics['Registration_Rate'] = (branch_metrics['Registered_Count'] / branch_metrics['Total_Accounts'] * 100).round(1)

# Add region info to branch metrics (based on a single branch's region)
branch_region = ntb_reg_tbl_df.groupby('BRANCH_NAME')['REGION_DESC'].first().reset_index()
branch_metrics = pd.merge(branch_metrics, branch_region, on='BRANCH_NAME')

# Identify top and bottom performing branches
top_branches = branch_metrics.sort_values('Registration_Rate', ascending=False).head(20)
bottom_branches = branch_metrics.sort_values('Registration_Rate').head(20)

# Save branch metrics
branch_metrics.to_excel('./Notebook_reports/branch_onboarding_performance.xlsx', index=False)

In [59]:
# Define funnel stages
funnel_data = {
    'Stage': ['Account Opening', 'Mobile Registration', 'Active in Last 30 Days', 'Weekly Active Users'],
    'Count': [
        len(ntb_reg_tbl_df),  # All accounts
        ntb_reg_tbl_df['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum(),  # All registered
        (ntb_reg_tbl_df['Login_Bracket'] == 'Last 30 Days').sum(),  # Active in last 30 days
        (ntb_reg_tbl_df['Login_Frequency'] == 'Weekly').sum()  # Log in weekly
    ]
}

# Create dataframe
funnel_df = pd.DataFrame(funnel_data)

# Calculate percentage of total accounts
funnel_df['Percentage'] = (funnel_df['Count'] / funnel_df['Count'][0] * 100).round(1)

# Calculate stage-to-stage conversion rates
funnel_df['Conversion_Rate'] = 100.0  # Initialize with a default value for all rows

# Update conversion rates for rows after the first one
for i in range(1, len(funnel_df)):
    # Conversion from previous stage to current stage
    funnel_df.loc[i, 'Conversion_Rate'] = (funnel_df['Count'][i] / funnel_df['Count'][i-1] * 100).round(1)

# Add stage drop-off
funnel_df['Drop_Off'] = 100 - funnel_df['Conversion_Rate']

print("Customer Journey Funnel:")
print(funnel_df)


# Export to Excel for dashboard
funnel_df.to_excel('./Notebook_reports/customer_journey_funnel.xlsx', index=False)

Customer Journey Funnel:
                    Stage   Count  Percentage  Conversion_Rate  Drop_Off
0         Account Opening  354815       100.0            100.0       0.0
1     Mobile Registration  193295        54.5             54.5      45.5
2  Active in Last 30 Days  120128        33.9             62.1      37.9
3     Weekly Active Users   64458        18.2             53.7      46.3

In [60]:
# Create funnel by region
regions = ntb_reg_tbl_df['REGION_DESC'].unique()
region_funnels = []

for region in regions:
    region_data = ntb_reg_tbl_df[ntb_reg_tbl_df['REGION_DESC'] == region]
    
    funnel = {
        'Region': region,
        'Total_Accounts': len(region_data),
        'Registered': region_data['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum(),
        'Active_30_Days': (region_data['Login_Bracket'] == 'Last 30 Days').sum(),
        'Weekly_Users': (region_data['Login_Frequency'] == 'Weekly').sum()
    }
    
    region_funnels.append(funnel)

region_funnel_df = pd.DataFrame(region_funnels)

# Calculate conversion rates
region_funnel_df['Registration_Rate'] = (region_funnel_df['Registered'] / region_funnel_df['Total_Accounts'] * 100).round(1)
region_funnel_df['Activation_Rate'] = (region_funnel_df['Active_30_Days'] / region_funnel_df['Registered'] * 100).round(1)
region_funnel_df['Weekly_Usage_Rate'] = (region_funnel_df['Weekly_Users'] / region_funnel_df['Active_30_Days'] * 100).round(1)

# Sort by Registration Rate
region_funnel_df = region_funnel_df.sort_values('Registration_Rate', ascending=False)

# Print the regional funnel analysis
print("\nRegional Funnel Analysis:")
print(region_funnel_df)

# Save to Excel
region_funnel_df.to_excel('./Notebook_reports/regional_funnel_analysis.xlsx', index=False)

Regional Funnel Analysis:
                Region  Total_Accounts  Registered  Active_30_Days  \
10     South Region-II           34241       23727            9227
7     Central Region-I           39595       25861           17117
6       South Region-I           33623       20810           11125
1      North Region-II           35573       20439           15255
3       North Region-I           39126       20699           14756
4   Central Region-III           30222       15819            9412
5             IB North           25940       12764            8702
9    IB Central Lahore           25335       12280            8122
0    Central Region-II           48956       22112           13588
8     IB South Karachi           12506        5649            3332
2     North Region-III           29698       13135            9492

    Weekly_Users  Registration_Rate  Activation_Rate  Weekly_Usage_Rate
10          4619               69.3             38.9               50.1
7           9728               65.3             66.2               56.8
6           5452               61.9             53.5               49.0
1           8721               57.5             74.6               57.2
3           8393               52.9             71.3               56.9
4           4949               52.3             59.5               52.6
5           4733               49.2             68.2               54.4
9           4322               48.5             66.1               53.2
0           6868               45.2             61.5               50.5
8           1643               45.2             59.0               49.3
2           5030               44.2             72.3               53.0

In [61]:
# Group by account opening month
ntb_reg_tbl_df['Open_Month'] = pd.to_datetime(ntb_reg_tbl_df['Open_Date_']).dt.to_period('M')

# Create monthly cohorts and track their progression through the funnel
monthly_cohorts = []

for month in sorted(ntb_reg_tbl_df['Open_Month'].unique()):
    cohort = ntb_reg_tbl_df[ntb_reg_tbl_df['Open_Month'] == month]
    
    # Calculate funnel metrics for this cohort
    metrics = {
        'Cohort_Month': str(month),  # Convert to string for display
        'Total_Accounts': len(cohort),
        'Registered_30d': cohort[
            (cohort['Registration_Date'].notna()) & 
            ((cohort['Registration_Date'] - cohort['Open_Date_']).dt.days <= 30)
        ].shape[0],
        'Registered_90d': cohort[
            (cohort['Registration_Date'].notna()) & 
            ((cohort['Registration_Date'] - cohort['Open_Date_']).dt.days <= 90)
        ].shape[0]
    }
    
    monthly_cohorts.append(metrics)

monthly_funnel_df = pd.DataFrame(monthly_cohorts)
monthly_funnel_df['30d_Registration_Rate'] = (monthly_funnel_df['Registered_30d'] / monthly_funnel_df['Total_Accounts'] * 100).round(1)
monthly_funnel_df['90d_Registration_Rate'] = (monthly_funnel_df['Registered_90d'] / monthly_funnel_df['Total_Accounts'] * 100).round(1)

# Print the monthly cohort analysis
print("\nMonthly Cohort Analysis:")
print(monthly_funnel_df)

# Save to Excel
monthly_funnel_df.to_excel('./Notebook_reports/monthly_cohort_analysis.xlsx', index=False)

Monthly Cohort Analysis:
   Cohort_Month  Total_Accounts  Registered_30d  Registered_90d  \
0       2024-01           22712            3826            6806
1       2024-02           21241            3891            6360
2       2024-03           18600            3399            6482
3       2024-04           18402            3850            6878
4       2024-05           24764            5946            9093
5       2024-06           17623            4923            7285
6       2024-07           21829            6721            9501
7       2024-08           23573            7464           10531
8       2024-09           21926            6771            9991
9       2024-10           23601            7834           11811
10      2024-11           20690            8435           11222
11      2024-12           20740            8617           11215
12      2025-01           22120           10911           13521
13      2025-02           21873           11040           13182
14      2025-03           20770           10597           11926
15      2025-04           30041           12823           12843
16      2025-05            4310             734             734

    30d_Registration_Rate  90d_Registration_Rate
0                    16.8                   30.0
1                    18.3                   29.9
2                    18.3                   34.8
3                    20.9                   37.4
4                    24.0                   36.7
5                    27.9                   41.3
6                    30.8                   43.5
7                    31.7                   44.7
8                    30.9                   45.6
9                    33.2                   50.0
10                   40.8                   54.2
11                   41.5                   54.1
12                   49.3                   61.1
13                   50.5                   60.3
14                   51.0                   57.4
15                   42.7                   42.8
16                   17.0                   17.0

In [62]:
# Create summary metrics for dashboard
summary_metrics = {
    'Metric': [
        'Total Accounts',
        'Registered Accounts',
        'Registration Rate',
        'Active 30 Days',
        'Active Rate',
        'Avg Days to Onboard',
        'Already Registered',
        'Quick Onboarding (≤10 days)'
    ],
    'Value': [
        len(ntb_reg_tbl_df),
        ntb_reg_tbl_df['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum(),
        ntb_reg_tbl_df['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum() / len(ntb_reg_tbl_df) * 100,
        (ntb_reg_tbl_df['Login_Bracket'] == 'Last 30 Days').sum(),
        (ntb_reg_tbl_df['Login_Bracket'] == 'Last 30 Days').sum() / ntb_reg_tbl_df['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum() * 100,
        ntb_reg_tbl_df['Days_to_Onboard'].mean(),
        (ntb_reg_tbl_df['Registration_Remarks'] == 'Already Registered').sum(),
        ntb_reg_tbl_df['Onboarding_Time_Bracket'].isin(['5 days or less', '6-10 days']).sum() / ntb_reg_tbl_df['Registration_Remarks'].isin(['Registered', 'Already Registered']).sum() * 100
    ]
}

# Convert to DataFrame for easy export
summary_df = pd.DataFrame(summary_metrics)
summary_df['Value'] = summary_df['Value'].round(2)
print("\nSummary Metrics:")
print(summary_df)

# Export summary metrics to Excel
summary_df.to_excel('./Notebook_reports/Mobile_Banking_Summary_Metrics.xlsx', index=False)

Summary Metrics:
                        Metric      Value
0               Total Accounts  354815.00
1          Registered Accounts  193295.00
2            Registration Rate      54.48
3               Active 30 Days  120128.00
4                  Active Rate      62.15
5          Avg Days to Onboard      59.78
6           Already Registered   24544.00
7  Quick Onboarding (≤10 days)      18.60

In [63]:
# # Save the updated main dataframe with onboarding metrics
ntb_reg_tbl_df.to_excel('./Notebook_reports/NTB_Reg_Summary_with_Onboarding.xlsx', index=False)